### ISSUE TITLE
Same result on Chromium-based browsers

### ISSUE THREAD

**Issue by demonlite** [dchest/fast-sha256-js#4]
Some problem on Chromium-based browsers. (Maybe in other too.)
For two different passwords returns same result. 
For example:
```
console.log(sha256.pbkdf2('dsddsdsds1', '', 0, 32));
console.log(sha256.pbkdf2('sddsdsdse1', '', 0, 32));
```

**Comment by dchest** [comment]
Please read documentation:

> Functions accept and return Uint8Arrays. To convert strings, use external library (for example, nacl.util).
