### ISSUE TITLE
PKBDF2 Doesn't appear to generate exepcted values

### ISSUE THREAD

**Issue by PH0lder** [dchest/fast-sha256-js#6]
I am trying to get corresponding values between JavaScript code and Java code.  When that didn't happen, I went looking for test vectors, and added this function to my JavaScript, which fails to produce the expected output for the first test vector.

function doTestVectors() {
// Test vectors from https://stackoverflow.com/questions/5130513/pbkdf2-hmac-sha2-test-vectors
  result1   = toHexString(sha256.pbkdf2("password", "salt", 1, 32));
  expected1 = "120fb6cffcf8b32c43e7225256c4f837a86548c92ccc35480805987cb70be17b";
  if (result1 != expected1)
  {
    alert("Test failed. result1=" + result1);
  }
}

It produces:
Test failed. result1=a4a11ce5fbe8f96bf3028035286c2c9274cd4259cbc224e37a73d971923903d3

Perhaps you could add these known good test vectors to the code and then hopefully also get a match?

**Comment by dchest** [comment]
Hello,

Please see the README:

> Functions accept and return Uint8Arrays. To convert strings, use external library (for example, nacl.util).

https://github.com/dchest/fast-sha256-js#usage

**Comment by PH0lder** [comment]
Fair enough, I didn't see the existing about that before opening mine, and I apologize for my mistake.  Once I changed the code to:
function doTestVectors() {
// Test vectors from https://stackoverflow.com/questions/5130513/pbkdf2-hmac-sha2-test-vectors
  result1   = toHexString(sha256.pbkdf2(nacl.util.decodeUTF8("password"), nacl.util.decodeUTF8("salt"), 1, 32));
  expected1 = "120fb6cffcf8b32c43e7225256c4f837a86548c92ccc35480805987cb70be17b";
  if (result1 != expected1)
  {
    alert("Test failed.  result1=" + result1 + "  expected1=" + expected1);
  }
}

After that change it does indeed return the expected result.

However, since this seems a very easy mistake to make, I would encourage you to simply fail if the inputs are not of the correct type, rather than returning what appears to be correct results that are in fact a lie.  It's never nice to surprise the user with unexpected or undocumented behavior, especially when they naively appear to be doing everything correctly.

**Comment by dchest** [comment]
Good suggestion, I'll see if it makes performance much worse, and if it doesn't I'll add a type check. Thanks!
