### ISSUE TITLE
pbkdf2 gives always the same result

### ISSUE THREAD

**Issue by kostelnik** [dchest/fast-sha256-js#7]
pbkdf2 always gives me the same result regardless of the password:

sha256.pbkdf2('b', 'salt', 10, 32).join(',')
"234,39,191,6,86,158,63,177,246,157,96,178,195,13,125,54,91,1,37,107,241,3,140,34,21,102,65,171,57,106,121,67"

sha256.pbkdf2('a', 'salt', 10, 32).join(',')
"234,39,191,6,86,158,63,177,246,157,96,178,195,13,125,54,91,1,37,107,241,3,140,34,21,102,65,171,57,106,121,67"
﻿
What am I doing wrong?
￼

**Comment by dchest** [comment]
You are using strings instead of `Uint8Array`s: https://github.com/dchest/fast-sha256-js#usage

**Comment by kostelnik** [comment]
thanks
